spring:
  datasource:
    url: ${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=MyCropDiary;encrypt=true;trustServerCertificate=true}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:090504}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: none
